# Generated by Django 5.2.15 on 2026-06-07 21:28

import apps.core.managers
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=180, unique=True)),
                ('password', models.TextField(db_column='password_hash')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('documento_identidad', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
            managers=[
                ('objects', apps.core.managers.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('cod_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=120)),
                ('operacion', models.CharField(max_length=20)),
                ('cod_registro', models.TextField(blank=True, null=True)),
                ('usuario_bd', models.TextField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField()),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('cod_direccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=80)),
                ('receptor', models.CharField(max_length=180)),
                ('linea1', models.CharField(max_length=200)),
                ('linea2', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(max_length=120)),
                ('provincia', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=80)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('es_predeterminada', models.BooleanField()),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'direccion_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoMembresia',
            fields=[
                ('cod_estado_membresia', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'estado_membresia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('cod_estado_pago', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'estado_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('cod_estado_pedido', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(unique=True)),
                ('genera_tracking', models.BooleanField()),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('cod_estado_producto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('cod_intento', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=180)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('exitoso', models.BooleanField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_intento', models.DateTimeField()),
            ],
            options={
                'db_table': 'intento_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('clave', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'parametro_sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('cod_perfil', models.BigAutoField(primary_key=True, serialize=False)),
                ('acepta_marketing', models.BooleanField()),
                ('idioma_preferido', models.CharField(max_length=10)),
                ('moneda_preferida', models.CharField(max_length=10)),
                ('metadata', models.JSONField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'perfil_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('cod_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('cod_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('pk', models.CompositePrimaryKey('cod_rol', 'cod_permiso', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rol_permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEventoTracking',
            fields=[
                ('cod_tipo_evento', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_evento_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimientoInventario',
            fields=[
                ('cod_tipo_movimiento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('signo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'tipo_movimiento_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('pk', models.CompositePrimaryKey('cod_usuario', 'cod_rol', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario_rol',
                'managed': False,
            },
        ),
    ]
