from django.urls import path
from . import views

app_name = "administracion"

urlpatterns = [
    path("", views.panel_view, name="panel"),

    path("api/resumen/", views.api_resumen, name="api_resumen"),
    path("api/productos/", views.api_productos_admin, name="api_productos_admin"),
    path("api/productos/<int:cod_producto>/publicar/", views.api_publicar_producto, name="api_publicar_producto"),
    path("api/productos/<int:cod_producto>/pausar/", views.api_pausar_producto, name="api_pausar_producto"),
    path("api/productos/<int:cod_producto>/desactivar/", views.api_desactivar_producto, name="api_desactivar_producto"),
    path("api/productos/crear/", views.api_producto_admin, name="api_crear_producto"),
    path("api/productos/crear-integral/", views.api_producto_integral_admin, name="api_crear_producto_integral"),
    path("api/productos/<int:cod_producto>/actualizar/", views.api_producto_admin, name="api_actualizar_producto"),
    path("api/productos/<int:cod_producto>/validar-publicable/", views.api_validar_producto_publicable, name="api_validar_producto_publicable"),
    path("api/productos/<int:cod_producto>/gestion/", views.api_gestion_producto_admin, name="api_gestion_producto"),
    path("api/productos/<int:cod_producto>/imagenes/", views.api_imagen_producto_admin, name="api_imagen_producto"),
    path("api/productos/<int:cod_producto>/archivos/", views.api_archivo_producto_admin, name="api_archivo_producto"),
    path("api/productos/<int:cod_producto>/limite/", views.api_limite_producto_admin, name="api_limite_producto"),
    path("api/productos/<int:cod_producto>/relacionados/", views.api_relacion_producto_admin, name="api_relacion_producto"),
    path("api/productos/<int:cod_producto>/moderacion/", views.api_moderacion_producto_admin, name="api_moderacion_producto"),
    path("api/imagenes/<int:cod_imagen>/", views.api_imagen_admin, name="api_imagen_admin"),
    path("api/atributos/", views.api_atributo_producto_admin, name="api_crear_atributo_producto"),
    path("api/atributos/<int:cod_atributo>/", views.api_atributo_producto_admin, name="api_actualizar_atributo_producto"),
    path("api/atributos/valores/", views.api_valor_atributo_producto_admin, name="api_valor_atributo_producto"),
    path("api/productos/<int:cod_producto>/recalcular-precio/", views.api_recalcular_precio_producto, name="api_recalcular_precio_producto"),
    path("api/catalogo/", views.api_catalogo_admin, name="api_catalogo_admin"),
    path("api/categorias/", views.api_categoria_admin, name="api_crear_categoria"),
    path("api/categorias/<int:cod_categoria>/", views.api_categoria_admin, name="api_actualizar_categoria"),
    path("api/marcas/", views.api_marca_admin, name="api_crear_marca"),
    path("api/marcas/<int:cod_marca>/", views.api_marca_admin, name="api_actualizar_marca"),
    path("api/reglas-precio/", views.api_regla_precio_admin, name="api_crear_regla_precio"),
    path("api/reglas-precio/<int:cod_regla_precio>/", views.api_regla_precio_admin, name="api_actualizar_regla_precio"),
    path("api/inventario/", views.api_inventario, name="api_inventario"),
    path("api/inventario/lotes/", views.api_lotes_admin, name="api_lotes_admin"),
    path("api/inventario/lotes/crear/", views.api_lote_admin, name="api_crear_lote"),
    path("api/inventario/alertas/", views.api_alertas_stock_admin, name="api_alertas_stock_admin"),
    path("api/inventario/acciones/", views.api_accion_inventario_admin, name="api_accion_inventario_admin"),
    path("api/pedidos/", views.api_pedidos_admin, name="api_pedidos_admin"),
    path("api/pedidos/<int:cod_pedido>/estado/", views.api_cambiar_estado_pedido, name="api_cambiar_estado_pedido"),
    path("api/pedidos/<int:cod_pedido>/detalle/", views.api_detalle_pedido_admin, name="api_detalle_pedido_admin"),
    path("api/proveedores/", views.api_proveedores_admin, name="api_proveedores_admin"),
    path("api/proveedores/crear/", views.api_proveedor_admin, name="api_crear_proveedor"),
    path("api/proveedores/<int:cod_proveedor>/", views.api_proveedor_admin, name="api_actualizar_proveedor"),
    path("api/proveedores/<int:cod_proveedor>/contactos/", views.api_contacto_proveedor_admin, name="api_contacto_proveedor"),
    path("api/proveedores/usuarios/", views.api_usuario_proveedor_admin, name="api_usuario_proveedor_admin"),
    path("api/producto-proveedor/", views.api_producto_proveedor_admin, name="api_producto_proveedor"),
    path("api/abastecimiento/", views.api_abastecimiento_admin, name="api_abastecimiento_admin"),
    path("api/abastecimiento/<int:cod_orden_abastecimiento>/accion/", views.api_accion_abastecimiento_admin, name="api_accion_abastecimiento_admin"),
    path("api/cupones/", views.api_cupon_admin, name="api_crear_cupon"),
    path("api/cupones/<int:cod_cupon>/", views.api_cupon_admin, name="api_actualizar_cupon"),
    path("api/promociones/", views.api_promocion_admin, name="api_crear_promocion"),
    path("api/promociones/<int:cod_promocion>/", views.api_promocion_admin, name="api_actualizar_promocion"),
    path("api/promociones/<int:cod_promocion>/productos/", views.api_promocion_producto_admin, name="api_promocion_producto"),
    path("api/promociones/<int:cod_promocion>/categorias/", views.api_promocion_categoria_admin, name="api_promocion_categoria"),
    path("api/pagos/", views.api_pagos_admin, name="api_pagos_admin"),
    path("api/tracking/", views.api_tracking_admin, name="api_tracking_admin"),
    path("api/tracking/acciones/", views.api_accion_tracking_admin, name="api_accion_tracking_admin"),
    path("api/prime/", views.api_prime_admin, name="api_prime_admin"),
    path("api/prime/beneficios/", views.api_beneficio_prime_admin, name="api_crear_beneficio_prime"),
    path("api/prime/beneficios/<int:cod_beneficio>/", views.api_beneficio_prime_admin, name="api_actualizar_beneficio_prime"),
    path("api/reportes/ventas/", views.api_reporte_ventas, name="api_reporte_ventas"),
    path("api/control-empresarial/", views.api_control_empresarial_admin, name="api_control_empresarial"),
    path("api/control-empresarial/acciones/", views.api_accion_empresarial_admin, name="api_accion_empresarial"),
]
